version: "3.7"
services:
  jooqRecordListenerDB:
    image: postgres:15.2
    container_name: jooqRecordListenerDB
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jooqRecordListenerDB
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: 'UTC'
    command: postgres -c listen_addresses='*'
    ports:
      - "25432:5432"